cs291a_proj3_final/app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "users#index"

  get 'users', to: 'users#index'
  get 'users/show/:id', to: 'users#show'  
  get 'users/new', to: 'users#new'

  get 'users/:user_id/posts', to: 'posts#index', as: :user_post
  get 'users/:user_id/posts/:id', to: 'posts#show', as: :post
  get 'users/:user_id/posts/:id/new', to: 'posts#new', as: :new_post

  #get 'users/:user_id/posts/:id/edit', to: 'posts#edit', as: :edit_post

  get 'users/:user_id/posts/:post_id/comments/:id/new', to: 'comments#new', as: :new_comment
  get 'users/:user_id/posts/:post_id/comments', to: 'comments#new', as: :user_post_comments
  get 'users/:user_id/posts/:id', to: "posts#show", as: :test

  #delete 'users/:user_id/posts/:id', to: 'posts#destroy', as: :destroy_post

  resources :users do
    resources :posts do
      resources :comments
    end
  end


  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
  # Defines the root path route ("/")
  # root "posts#index"
end

cs291a_proj3_final/app/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

cs291a_proj3_final/app/app/controllers/posts_controller.rb
# app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_user
    before_action :set_post, only: [:show, :edit, :update, :destroy]
  
    # GET /users/:user_id/posts
    def index
      @posts = @user.posts
    end
  
    # GET /users/:user_id/posts/1
    def show
        @post
    end
  
    # GET /users/:user_id/posts/new
    def new
      @post = @user.posts.build
    end
  
    # GET /users/:user_id/posts/1/edit
    def edit
    end
  
    # POST /users/:user_id/posts
    def create
      @post = @user.posts.build(post_params)
  
      if @post.save
        redirect_to user_path(@user), notice: 'Post was successfully created.'
      else
        render :new
      end
    end
  
    # PATCH/PUT /users/:user_id/posts/1
    def update
      if @post.update(post_params)
        redirect_to post_path(@user, @post), notice: 'Post was successfully updated.'
      else
        render :edit
      end
    end
  
    # DELETE /users/:user_id/posts/1
    def destroy
      @post.destroy
      redirect_to user_path(@user), notice: 'Post was successfully destroyed.'
    end
  
    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end
  
    def set_post
      @post = @user.posts.find(params[:id])
    end
  
    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
  end
  

=begin
class PostsController < ApplicationController
    #before_action :get_user
    def index
        #@user = User.find(params[:id])
        @posts = Post.all
    end
    
    def show
        @user = User.find(params[:id])
        @post = @user.posts.find()
    end
      
    def new
        @user = User.find(params[:user_id])
        @post = @user.posts
    end

    def create
        @user = User.find(params[:user_id])
        @post = @user.posts.create(post_params)
        
        if @user.save
            redirect_to user_path(@user)
          else
            render :new, status: :unprocessable_entity
          end
    end
    
    def edit
        #@post = Post.find(params[:id])
        @user = User.find(params[:user_id])
        @post = @user.posts.find(params[:id])
    end
    
    def update
        @user = User.find(params[:id])
        post = @user.posts.find(params[:id])

        if @post.update(post_params)
          redirect_to @post
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @user = User.find(params[:user_id])
        @post = @user.posts.find(params[:id])
        @post.destroy
        
        redirect_to user_path(user), status: :see_other
    end
    
    private
        def post_params
            params.require(:post).permit(:title, :body)
        end

        #def get_user
        #    @puserost = User.find(params[:id])
        #end
end
=end

cs291a_proj3_final/app/app/helpers/posts_helper.rb
module PostsHelper
end

cs291a_proj3_final/app/app/views/posts/_form.html.erb
<%= form_with model: [@user, @user.posts.build ] do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

cs291a_proj3_final/app/app/views/posts/_post.html.erb
<p>
  <strong>Title:</strong>
  <%= post.title %>
</p>

<p>
  <strong>Post:</strong>
  <%= post.body %>
</p>

<p>
    <%= link_to "Destroy Post", [@post, post], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
</p>

cs291a_proj3_final/app/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_with(model: [@user, @post], url: post_path(@user, @post), local: true) do |form| %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

cs291a_proj3_final/app/app/views/posts/index.html.erb
<h1>Posts</h1>
<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.body, user_post_path(@user, post) %></li>
  <% end %>
</ul>

cs291a_proj3_final/app/app/views/posts/index_old.html.erb
<h1>Posts</h1>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, user_post_path(post.user) %>
    </li>
  <% end %>
</ul>

cs291a_proj3_final/app/app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_with(model: [@user, @post], url: user_post_path(@user), local: true) do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

cs291a_proj3_final/app/app/views/posts/new_old.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

cs291a_proj3_final/app/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<%= link_to 'Edit', edit_user_post_path(@user, @post) %>
<%= link_to "Delete Post", post_path(@user, @post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

<%= link_to 'New Comment', new_user_post_comment_path(@user, @post) %>

<h2>Comments:</h2>
<ul>
  <% @post.comments.each do |comment| %>
    <li><%= comment.commenter + ": " + comment.body %></li>
    <%= link_to "Delete Comment", user_post_comment_path(@user, @post, comment), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  <% end %>
</ul>

cs291a_proj3_final/app/app/views/posts/show_old.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>

<ul>
  <li><%= link_to "Edit Post", edit_post_path(@post) %></li>
  <li><%= link_to "Destroy Post", post_path(@post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>