cs291a_proj3_final/app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "users#index"

  get 'users', to: 'users#index'
  get 'users/show/:id', to: 'users#show'  
  get 'users/new', to: 'users#new'

  get 'users/:user_id/posts', to: 'posts#index', as: :user_post
  get 'users/:user_id/posts/:id', to: 'posts#show', as: :post
  get 'users/:user_id/posts/:id/new', to: 'posts#new', as: :new_post

  #get 'users/:user_id/posts/:id/edit', to: 'posts#edit', as: :edit_post

  get 'users/:user_id/posts/:post_id/comments/:id/new', to: 'comments#new', as: :new_comment
  get 'users/:user_id/posts/:post_id/comments', to: 'comments#new', as: :user_post_comments
  get 'users/:user_id/posts/:id', to: "posts#show", as: :test

  #delete 'users/:user_id/posts/:id', to: 'posts#destroy', as: :destroy_post

  resources :users do
    resources :posts do
      resources :comments
    end
  end


  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
  # Defines the root path route ("/")
  # root "posts#index"
end

cs291a_proj3_final/app/app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
  
    validates :name, presence: true
    validates :email, presence: true
end

cs291a_proj3_final/app/app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @posts = @user.posts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    if (@user = User.find_by_id(params[:id]).present?)
      @user = User.find(params[:id])
      #@posts = @user.posts
    else
      raise ActiveRecord::RecordNotFound.new()
    end
    #@user = User.find(params[:id])
  #rescue ActiveRecord::RecordNotFound
    #render file: "#{Rails.root}/public/404.html", layout: false, status: :not_found
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:name, :email)
  end
end
=begin
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    if (@user = User.find_by_id(params[:id]).present?)
      @user = User.find(params[:id])
      @posts = @user.posts
    else
      raise ActiveRecord::RecordNotFound.new()
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path :see_other
  end

  def posts
    @user = User.find(params[:id])
    @posts = @user.posts
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email)
    end
end
=end

cs291a_proj3_final/app/app/helpers/users_helper.rb
module UsersHelper
end

cs291a_proj3_final/app/app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% user.errors.full_messages_for(:email).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :email %><br>
      <%= form.text_field :email %>
      <% user.errors.full_messages_for(:email).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

cs291a_proj3_final/app/app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= form_with(model: @user, url: user_path(@user), method: :patch, local: true) do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

cs291a_proj3_final/app/app/views/users/edit_old.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

cs291a_proj3_final/app/app/views/users/index.html.erb
<h1>Users</h1>

Our blog has <%= User.count %> users and counting!

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

<%= link_to 'New User', new_user_path %>

cs291a_proj3_final/app/app/views/users/new.html.erb
<h1>New User</h1>
<%= form_with(model: @user, url: users_path, local: true) do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

cs291a_proj3_final/app/app/views/users/new_old.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

cs291a_proj3_final/app/app/views/users/posts.html.erb
<h1>Posts</h1>

This user has <%= @user.posts.count %> posts and counting!

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post %>
    </li>
  <% end %>
</ul>

<%= link_to "New Post", new_post_path %>

cs291a_proj3_final/app/app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->
<h1><%= @user.name %></h1>
<p><strong>Email:</strong> <%= @user.email %></p>

<%= link_to 'Edit user', edit_user_path(@user) %> 
<%= link_to "Delete User", user_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

<%= link_to 'New Post', new_post_path(@user) %>

<!-- Display links to all the user's posts -->
<h2>Posts:</h2>
<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(@user, post) %></li>
  <% end %>
</ul>

cs291a_proj3_final/app/app/views/users/show_old.html.erb
<h1><%= @user.name %></h1>

<ul>
  <li><%= link_to "Edit User", edit_user_path(@user) %></li>
  <li><%= link_to "Destroy User", user_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<%= link_to "New Post", new_post_path(@user) %>

<%= link_to "Post List", user_posts_path(@user) %>

<h2>Posts</h2>
<%= render @user.posts %>