cs291a_proj3_final/app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "users#index"

  get 'users', to: 'users#index'
  get 'users/show/:id', to: 'users#show'  
  get 'users/new', to: 'users#new'

  get 'users/:user_id/posts', to: 'posts#index', as: :user_post
  get 'users/:user_id/posts/:id', to: 'posts#show', as: :post
  get 'users/:user_id/posts/:id/new', to: 'posts#new', as: :new_post

  #get 'users/:user_id/posts/:id/edit', to: 'posts#edit', as: :edit_post

  get 'users/:user_id/posts/:post_id/comments/:id/new', to: 'comments#new', as: :new_comment
  get 'users/:user_id/posts/:post_id/comments', to: 'comments#new', as: :user_post_comments
  get 'users/:user_id/posts/:id', to: "posts#show", as: :test

  #delete 'users/:user_id/posts/:id', to: 'posts#destroy', as: :destroy_post

  resources :users do
    resources :posts do
      resources :comments
    end
  end


  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
  # Defines the root path route ("/")
  # root "posts#index"
end

cs291a_proj3_final/app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post, optional: true
end

cs291a_proj3_final/app/app/controllers/comments_controller.rb
# app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_user_and_post
    before_action :set_comment, only: [:show, :edit, :update, :destroy]
  
    # GET /users/:user_id/posts/:post_id/comments
    def index
      @comments = @post.comments
    end
  
    # GET /users/:user_id/posts/:post_id/comments/1
    def show
        @comment
    end
  
    # GET /users/:user_id/posts/:post_id/comments/new
    def new
      @comment = @post.comments.build
    end
  
    # GET /users/:user_id/posts/:post_id/comments/1/edit
    def edit
    end
  
    # POST /users/:user_id/posts/:post_id/comments
    def create
      @comment = @post.comments.build(comment_params)
  
      if @comment.save
        redirect_to post_path(@user, @post), notice: 'Comment was successfully created.'
      else
        render :new
      end
    end
  
    # PATCH/PUT /users/:user_id/posts/:post_id/comments/1
    def update
      if @comment.update(comment_params)
        redirect_to user_post_comment_path(@user, @post, @comment), notice: 'Comment was successfully updated.'
      else
        render :edit
      end
    end
  
    # DELETE /users/:user_id/posts/:post_id/comments/1
    def destroy
      @comment.destroy
      redirect_to post_path(@user, @post), notice: 'Comment was successfully destroyed.'
    end
  
    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_user_and_post
      @user = User.find(params[:user_id])
      @post = @user.posts.find(params[:post_id])
    end
  
    def set_comment
      @comment = @post.comments.find(params[:id])
    end
  
    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
  end

cs291a_proj3_final/app/app/helpers/comments_helper.rb
module CommentsHelper
end

cs291a_proj3_final/app/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

cs291a_proj3_final/app/app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

cs291a_proj3_final/app/app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= form_with(model: [@user, @post, @comment], url: user_post_comment_path(@user, @post, @comment), method: :patch, local: true) do |form| %>
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

cs291a_proj3_final/app/app/views/comments/index.html.erb
<h1>Comments</h1>
<ul>
  <% @comments.each do |comment| %>
    <li><%= comment.body %></li>
  <% end %>
</ul>

cs291a_proj3_final/app/app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= form_with(model: [@user, @post, @comment], url: user_post_comments_path(@user, @post), local: true) do |form| %>
  <div>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </div>
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

cs291a_proj3_final/app/app/views/comments/show.html.erb
<h1><%= @comment.commenter %></h1>
<p><%= @comment.body %></p>